//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvAudioMirror.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvAudioMirror.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Audio Mirror.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute TV.
        /// </summary>
        internal static string Button_Mute {
            get {
                return ResourceManager.GetString("Button_Mute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unmute TV.
        /// </summary>
        internal static string Button_Unmute {
            get {
                return ResourceManager.GetString("Button_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sound settings.
        /// </summary>
        internal static string Button_SoundSettings {
            get {
                return ResourceManager.GetString("Button_SoundSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-refresh when default device changes.
        /// </summary>
        internal static string Check_Auto {
            get {
                return ResourceManager.GetString("Check_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close TV Audio Mirror?.
        /// </summary>
        internal static string Confirm_Exit_Text {
            get {
                return ResourceManager.GetString("Confirm_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm_Exit_Title {
            get {
                return ResourceManager.GetString("Confirm_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app mirrors the audio from your default playback device to the first output whose name contains &quot;TV&quot;. If the default device is already a TV, nothing is done..
        /// </summary>
        internal static string Info_Text {
            get {
                return ResourceManager.GetString("Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current source: (error).
        /// </summary>
        internal static string Label_Source_Error {
            get {
                return ResourceManager.GetString("Label_Source_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current source: (unknown).
        /// </summary>
        internal static string Label_Source_Unknown {
            get {
                return ResourceManager.GetString("Label_Source_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current source: {0}.
        /// </summary>
        internal static string Label_Source_Value {
            get {
                return ResourceManager.GetString("Label_Source_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target TV: (default device is already a TV).
        /// </summary>
        internal static string Label_Tv_DefaultIsTV {
            get {
                return ResourceManager.GetString("Label_Tv_DefaultIsTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target TV: (not found).
        /// </summary>
        internal static string Label_Tv_NotFound {
            get {
                return ResourceManager.GetString("Label_Tv_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target TV: {0}.
        /// </summary>
        internal static string Label_Tv_Value {
            get {
                return ResourceManager.GetString("Label_Tv_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start mirroring..
        /// </summary>
        internal static string Log_CaptureError {
            get {
                return ResourceManager.GetString("Log_CaptureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirroring started: {0} → {1}.
        /// </summary>
        internal static string Log_CaptureStarted {
            get {
                return ResourceManager.GetString("Log_CaptureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default playback device changed: {0}.
        /// </summary>
        internal static string Log_DefaultChanged {
            get {
                return ResourceManager.GetString("Log_DefaultChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default playback device is already a TV. Mirroring is disabled..
        /// </summary>
        internal static string Log_DefaultIsTv {
            get {
                return ResourceManager.GetString("Log_DefaultIsTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read default playback device..
        /// </summary>
        internal static string Log_DefaultReadError {
            get {
                return ResourceManager.GetString("Log_DefaultReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV mute = {0}.
        /// </summary>
        internal static string Log_Mute {
            get {
                return ResourceManager.GetString("Log_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not mute TV..
        /// </summary>
        internal static string Log_MuteError {
            get {
                return ResourceManager.GetString("Log_MuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output containing &quot;TV&quot; was found. Rename your TV in sound settings..
        /// </summary>
        internal static string Log_NoTvFound {
            get {
                return ResourceManager.GetString("Log_NoTvFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open sound settings..
        /// </summary>
        internal static string Log_OpenSoundError {
            get {
                return ResourceManager.GetString("Log_OpenSoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while polling audio devices..
        /// </summary>
        internal static string Log_TimerError {
            get {
                return ResourceManager.GetString("Log_TimerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV volume = {0}%.
        /// </summary>
        internal static string Log_Volume {
            get {
                return ResourceManager.GetString("Log_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change TV volume..
        /// </summary>
        internal static string Log_VolumeError {
            get {
                return ResourceManager.GetString("Log_VolumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Tray_Reload {
            get {
                return ResourceManager.GetString("Tray_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Tray_Open {
            get {
                return ResourceManager.GetString("Tray_Open", resourceCulture);
            }
        }
    }
}
